#!/bin/sh

##############################################################################
#
#  Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link to app home
APP_HOME=$(dirname "$0")
while [ -h "$APP_HOME" ] ; do APP_HOME=$(dirname "$APP_HOME"); done
APP_HOME_NAME=$(basename "$APP_HOME")
APP_BASE_NAME=${APP_HOME_NAME}
APP_BASE_DIR=${APP_DIR_NAME%/..}

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='""

# Use the maximum available, or set MAX_FD != -1 then use that value.
MAX_FD="maximum"

warn () {
    echo "$*"
    >&2 echo
}

die () {
    warn
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "`uname`" in
  CYGWIN*)
    cygwin=true
    ;;
  Darwin*)
    darwin=true
    ;;
  MINGW*)
    msys=true
    ;;
  MSYS*|MSYS*)
    msys=true
    ;;
  NONSTOP*)
    nonstop=true
    ;;
esac

# For Cygwin, switch paths to Windows format before running java
if "$cygwin" = true ; then
    APP_HOME=`cygpath --path --mixed "$APP_HOME"`
else
    APP_HOME=`echo "$APP_HOME" | sed "s@/\/*@|g"`
fi

# For MSYS, convert paths to Windows format before running java
if "$msys" = true ; then
    APP_HOME=`echo "$APP_HOME" | sed "s@/\/*@|g"`
fi

# For Darwin, use classes.jar for backwards compatibility
if "$darwin" = true ; then
    GRADLE_APP_JAVACMD="$JAVA_HOME/bin/javac"
else
    GRADLE_APP_JAVACMD="$JAVA_HOME/lib/tools.jar"
fi

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/bin/java" ]; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/bin/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
else
    JAVACMD="java"
    which java >/dev/null || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."

    if [ ! -x "$JAVACMD" ] ; then
        die "Error: JAVA_HOME is not defined and the javac command"
        "does not exist in your PATH.  Please set JAVA_HOME."
    fi
fi

# Escape application args
save () {
    for i do printf %s\\n "$i" | sed "s/'/'\\\\''/g"
}
echo printf "%s " "$@" | sed "s/'/'\\\\''/g"
# Build classpath
CLASSPATH=$APP_HOME/lib/gradle-launcher.jar

# Execute Gradle
exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS -classpath "$CLASSPATH" org.gradle.launcher.GradleMain "$@"
